// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MySQL.proto
// Protobuf C++ Version: 6.33.4

#ifndef MySQL_2eproto_2epb_2eh
#define MySQL_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "Common.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_MySQL_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_MySQL_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_MySQL_2eproto;
}  // extern "C"
namespace sql {
class sql_init;
struct sql_initDefaultTypeInternal;
extern sql_initDefaultTypeInternal _sql_init_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull sql_init_class_data_;
class sql_insert;
struct sql_insertDefaultTypeInternal;
extern sql_insertDefaultTypeInternal _sql_insert_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull sql_insert_class_data_;
class sql_node;
struct sql_nodeDefaultTypeInternal;
extern sql_nodeDefaultTypeInternal _sql_node_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull sql_node_class_data_;
}  // namespace sql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace sql {

// ===================================================================


// -------------------------------------------------------------------

class sql_init final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:sql.sql_init) */ {
 public:
  inline sql_init() : sql_init(nullptr) {}
  ~sql_init() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(sql_init* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(sql_init));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR sql_init(::google::protobuf::internal::ConstantInitialized);

  inline sql_init(const sql_init& from) : sql_init(nullptr, from) {}
  inline sql_init(sql_init&& from) noexcept
      : sql_init(nullptr, ::std::move(from)) {}
  inline sql_init& operator=(const sql_init& from) {
    CopyFrom(from);
    return *this;
  }
  inline sql_init& operator=(sql_init&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const sql_init& default_instance() {
    return *reinterpret_cast<const sql_init*>(
        &_sql_init_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(sql_init& a, sql_init& b) { a.Swap(&b); }
  inline void Swap(sql_init* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(sql_init* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  sql_init* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<sql_init>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const sql_init& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const sql_init& from) { sql_init::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(sql_init* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "sql.sql_init"; }

  explicit sql_init(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  sql_init(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const sql_init& from);
  sql_init(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, sql_init&& from) noexcept
      : sql_init(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIpFieldNumber = 1,
    kUserFieldNumber = 3,
    kPasswordFieldNumber = 4,
    kDbFieldNumber = 5,
    kPortFieldNumber = 2,
    kInitSizeFieldNumber = 6,
    kMaxSizeFieldNumber = 7,
    kTimeMaxFieldNumber = 8,
    kTimeOutFieldNumber = 9,
    kThreadPoolSizeFieldNumber = 10,
  };
  // string ip = 1;
  void clear_ip() ;
  const ::std::string& ip() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_ip(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_ip();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_ip();
  void set_allocated_ip(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_ip() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_ip(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_ip();

  public:
  // string user = 3;
  void clear_user() ;
  const ::std::string& user() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_user(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_user();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_user();
  void set_allocated_user(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_user() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_user(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_user();

  public:
  // string password = 4;
  void clear_password() ;
  const ::std::string& password() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_password(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_password();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_password();
  void set_allocated_password(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_password() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_password(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_password();

  public:
  // string db = 5;
  void clear_db() ;
  const ::std::string& db() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_db(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_db();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_db();
  void set_allocated_db(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_db() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_db(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_db();

  public:
  // uint32 port = 2;
  void clear_port() ;
  ::uint32_t port() const;
  void set_port(::uint32_t value);

  private:
  ::uint32_t _internal_port() const;
  void _internal_set_port(::uint32_t value);

  public:
  // uint32 InitSize = 6;
  void clear_initsize() ;
  ::uint32_t initsize() const;
  void set_initsize(::uint32_t value);

  private:
  ::uint32_t _internal_initsize() const;
  void _internal_set_initsize(::uint32_t value);

  public:
  // uint32 MaxSize = 7;
  void clear_maxsize() ;
  ::uint32_t maxsize() const;
  void set_maxsize(::uint32_t value);

  private:
  ::uint32_t _internal_maxsize() const;
  void _internal_set_maxsize(::uint32_t value);

  public:
  // uint32 TimeMax = 8;
  void clear_timemax() ;
  ::uint32_t timemax() const;
  void set_timemax(::uint32_t value);

  private:
  ::uint32_t _internal_timemax() const;
  void _internal_set_timemax(::uint32_t value);

  public:
  // uint32 TimeOut = 9;
  void clear_timeout() ;
  ::uint32_t timeout() const;
  void set_timeout(::uint32_t value);

  private:
  ::uint32_t _internal_timeout() const;
  void _internal_set_timeout(::uint32_t value);

  public:
  // uint32 ThreadPoolSize = 10;
  void clear_threadpoolsize() ;
  ::uint32_t threadpoolsize() const;
  void set_threadpoolsize(::uint32_t value);

  private:
  ::uint32_t _internal_threadpoolsize() const;
  void _internal_set_threadpoolsize(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:sql.sql_init)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 10,
                                   0, 45,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const sql_init& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr ip_;
    ::google::protobuf::internal::ArenaStringPtr user_;
    ::google::protobuf::internal::ArenaStringPtr password_;
    ::google::protobuf::internal::ArenaStringPtr db_;
    ::uint32_t port_;
    ::uint32_t initsize_;
    ::uint32_t maxsize_;
    ::uint32_t timemax_;
    ::uint32_t timeout_;
    ::uint32_t threadpoolsize_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MySQL_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull sql_init_class_data_;
// -------------------------------------------------------------------

class sql_node final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:sql.sql_node) */ {
 public:
  inline sql_node() : sql_node(nullptr) {}
  ~sql_node() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(sql_node* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(sql_node));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR sql_node(::google::protobuf::internal::ConstantInitialized);

  inline sql_node(const sql_node& from) : sql_node(nullptr, from) {}
  inline sql_node(sql_node&& from) noexcept
      : sql_node(nullptr, ::std::move(from)) {}
  inline sql_node& operator=(const sql_node& from) {
    CopyFrom(from);
    return *this;
  }
  inline sql_node& operator=(sql_node&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const sql_node& default_instance() {
    return *reinterpret_cast<const sql_node*>(
        &_sql_node_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(sql_node& a, sql_node& b) { a.Swap(&b); }
  inline void Swap(sql_node* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(sql_node* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  sql_node* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<sql_node>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const sql_node& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const sql_node& from) { sql_node::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(sql_node* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "sql.sql_node"; }

  explicit sql_node(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  sql_node(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const sql_node& from);
  sql_node(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, sql_node&& from) noexcept
      : sql_node(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMsgFieldNumber = 3,
    kHeadFieldNumber = 1,
    kTypeFieldNumber = 2,
  };
  // string msg = 3;
  void clear_msg() ;
  const ::std::string& msg() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_msg(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_msg();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_msg();
  void set_allocated_msg(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_msg() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_msg(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_msg();

  public:
  // .common.header head = 1;
  bool has_head() const;
  void clear_head() ;
  const ::common::header& head() const;
  [[nodiscard]] ::common::header* PROTOBUF_NULLABLE release_head();
  ::common::header* PROTOBUF_NONNULL mutable_head();
  void set_allocated_head(::common::header* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_head(::common::header* PROTOBUF_NULLABLE value);
  ::common::header* PROTOBUF_NULLABLE unsafe_arena_release_head();

  private:
  const ::common::header& _internal_head() const;
  ::common::header* PROTOBUF_NONNULL _internal_mutable_head();

  public:
  // int32 type = 2;
  void clear_type() ;
  ::int32_t type() const;
  void set_type(::int32_t value);

  private:
  ::int32_t _internal_type() const;
  void _internal_set_type(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:sql.sql_node)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   1, 24,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const sql_node& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr msg_;
    ::common::header* PROTOBUF_NULLABLE head_;
    ::int32_t type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MySQL_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull sql_node_class_data_;
// -------------------------------------------------------------------

class sql_insert final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:sql.sql_insert) */ {
 public:
  inline sql_insert() : sql_insert(nullptr) {}
  ~sql_insert() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(sql_insert* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(sql_insert));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR sql_insert(::google::protobuf::internal::ConstantInitialized);

  inline sql_insert(const sql_insert& from) : sql_insert(nullptr, from) {}
  inline sql_insert(sql_insert&& from) noexcept
      : sql_insert(nullptr, ::std::move(from)) {}
  inline sql_insert& operator=(const sql_insert& from) {
    CopyFrom(from);
    return *this;
  }
  inline sql_insert& operator=(sql_insert&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const sql_insert& default_instance() {
    return *reinterpret_cast<const sql_insert*>(
        &_sql_insert_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(sql_insert& a, sql_insert& b) { a.Swap(&b); }
  inline void Swap(sql_insert* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(sql_insert* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  sql_insert* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<sql_insert>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const sql_insert& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const sql_insert& from) { sql_insert::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(sql_insert* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "sql.sql_insert"; }

  explicit sql_insert(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  sql_insert(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const sql_insert& from);
  sql_insert(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, sql_insert&& from) noexcept
      : sql_insert(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHeadFieldNumber = 1,
  };
  // .common.header head = 1;
  bool has_head() const;
  void clear_head() ;
  const ::common::header& head() const;
  [[nodiscard]] ::common::header* PROTOBUF_NULLABLE release_head();
  ::common::header* PROTOBUF_NONNULL mutable_head();
  void set_allocated_head(::common::header* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_head(::common::header* PROTOBUF_NULLABLE value);
  ::common::header* PROTOBUF_NULLABLE unsafe_arena_release_head();

  private:
  const ::common::header& _internal_head() const;
  ::common::header* PROTOBUF_NONNULL _internal_mutable_head();

  public:
  // @@protoc_insertion_point(class_scope:sql.sql_insert)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const sql_insert& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::common::header* PROTOBUF_NULLABLE head_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MySQL_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull sql_insert_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// sql_node

// .common.header head = 1;
inline bool sql_node::has_head() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.head_ != nullptr);
  return value;
}
inline const ::common::header& sql_node::_internal_head() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::common::header* p = _impl_.head_;
  return p != nullptr ? *p : reinterpret_cast<const ::common::header&>(::common::_header_default_instance_);
}
inline const ::common::header& sql_node::head() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:sql.sql_node.head)
  return _internal_head();
}
inline void sql_node::unsafe_arena_set_allocated_head(
    ::common::header* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.head_);
  }
  _impl_.head_ = reinterpret_cast<::common::header*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sql.sql_node.head)
}
inline ::common::header* PROTOBUF_NULLABLE sql_node::release_head() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::common::header* released = _impl_.head_;
  _impl_.head_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::common::header* PROTOBUF_NULLABLE sql_node::unsafe_arena_release_head() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:sql.sql_node.head)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::common::header* temp = _impl_.head_;
  _impl_.head_ = nullptr;
  return temp;
}
inline ::common::header* PROTOBUF_NONNULL sql_node::_internal_mutable_head() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.head_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::common::header>(GetArena());
    _impl_.head_ = reinterpret_cast<::common::header*>(p);
  }
  return _impl_.head_;
}
inline ::common::header* PROTOBUF_NONNULL sql_node::mutable_head()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::common::header* _msg = _internal_mutable_head();
  // @@protoc_insertion_point(field_mutable:sql.sql_node.head)
  return _msg;
}
inline void sql_node::set_allocated_head(::common::header* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.head_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.head_ = reinterpret_cast<::common::header*>(value);
  // @@protoc_insertion_point(field_set_allocated:sql.sql_node.head)
}

// int32 type = 2;
inline void sql_node::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t sql_node::type() const {
  // @@protoc_insertion_point(field_get:sql.sql_node.type)
  return _internal_type();
}
inline void sql_node::set_type(::int32_t value) {
  _internal_set_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:sql.sql_node.type)
}
inline ::int32_t sql_node::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.type_;
}
inline void sql_node::_internal_set_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// string msg = 3;
inline void sql_node::clear_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& sql_node::msg() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:sql.sql_node.msg)
  return _internal_msg();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void sql_node::set_msg(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.msg_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:sql.sql_node.msg)
}
inline ::std::string* PROTOBUF_NONNULL sql_node::mutable_msg()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:sql.sql_node.msg)
  return _s;
}
inline const ::std::string& sql_node::_internal_msg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.msg_.Get();
}
inline void sql_node::_internal_set_msg(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL sql_node::_internal_mutable_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.msg_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE sql_node::release_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:sql.sql_node.msg)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.msg_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.msg_.Set("", GetArena());
  }
  return released;
}
inline void sql_node::set_allocated_msg(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.msg_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.msg_.IsDefault()) {
    _impl_.msg_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:sql.sql_node.msg)
}

// -------------------------------------------------------------------

// sql_init

// string ip = 1;
inline void sql_init::clear_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& sql_init::ip() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:sql.sql_init.ip)
  return _internal_ip();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void sql_init::set_ip(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.ip_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:sql.sql_init.ip)
}
inline ::std::string* PROTOBUF_NONNULL sql_init::mutable_ip()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_ip();
  // @@protoc_insertion_point(field_mutable:sql.sql_init.ip)
  return _s;
}
inline const ::std::string& sql_init::_internal_ip() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ip_.Get();
}
inline void sql_init::_internal_set_ip(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL sql_init::_internal_mutable_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.ip_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE sql_init::release_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:sql.sql_init.ip)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.ip_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.ip_.Set("", GetArena());
  }
  return released;
}
inline void sql_init::set_allocated_ip(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.ip_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.ip_.IsDefault()) {
    _impl_.ip_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:sql.sql_init.ip)
}

// uint32 port = 2;
inline void sql_init::clear_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint32_t sql_init::port() const {
  // @@protoc_insertion_point(field_get:sql.sql_init.port)
  return _internal_port();
}
inline void sql_init::set_port(::uint32_t value) {
  _internal_set_port(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:sql.sql_init.port)
}
inline ::uint32_t sql_init::_internal_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.port_;
}
inline void sql_init::_internal_set_port(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = value;
}

// string user = 3;
inline void sql_init::clear_user() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& sql_init::user() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:sql.sql_init.user)
  return _internal_user();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void sql_init::set_user(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.user_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:sql.sql_init.user)
}
inline ::std::string* PROTOBUF_NONNULL sql_init::mutable_user()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_user();
  // @@protoc_insertion_point(field_mutable:sql.sql_init.user)
  return _s;
}
inline const ::std::string& sql_init::_internal_user() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_.Get();
}
inline void sql_init::_internal_set_user(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL sql_init::_internal_mutable_user() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.user_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE sql_init::release_user() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:sql.sql_init.user)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.user_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.user_.Set("", GetArena());
  }
  return released;
}
inline void sql_init::set_allocated_user(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.user_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.user_.IsDefault()) {
    _impl_.user_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:sql.sql_init.user)
}

// string password = 4;
inline void sql_init::clear_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.password_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& sql_init::password() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:sql.sql_init.password)
  return _internal_password();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void sql_init::set_password(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.password_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:sql.sql_init.password)
}
inline ::std::string* PROTOBUF_NONNULL sql_init::mutable_password()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:sql.sql_init.password)
  return _s;
}
inline const ::std::string& sql_init::_internal_password() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.password_.Get();
}
inline void sql_init::_internal_set_password(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.password_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL sql_init::_internal_mutable_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.password_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE sql_init::release_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:sql.sql_init.password)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.password_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.password_.Set("", GetArena());
  }
  return released;
}
inline void sql_init::set_allocated_password(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.password_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.password_.IsDefault()) {
    _impl_.password_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:sql.sql_init.password)
}

// string db = 5;
inline void sql_init::clear_db() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.db_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& sql_init::db() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:sql.sql_init.db)
  return _internal_db();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void sql_init::set_db(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.db_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:sql.sql_init.db)
}
inline ::std::string* PROTOBUF_NONNULL sql_init::mutable_db()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_db();
  // @@protoc_insertion_point(field_mutable:sql.sql_init.db)
  return _s;
}
inline const ::std::string& sql_init::_internal_db() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.db_.Get();
}
inline void sql_init::_internal_set_db(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.db_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL sql_init::_internal_mutable_db() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.db_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE sql_init::release_db() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:sql.sql_init.db)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.db_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.db_.Set("", GetArena());
  }
  return released;
}
inline void sql_init::set_allocated_db(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.db_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.db_.IsDefault()) {
    _impl_.db_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:sql.sql_init.db)
}

// uint32 InitSize = 6;
inline void sql_init::clear_initsize() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.initsize_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::uint32_t sql_init::initsize() const {
  // @@protoc_insertion_point(field_get:sql.sql_init.InitSize)
  return _internal_initsize();
}
inline void sql_init::set_initsize(::uint32_t value) {
  _internal_set_initsize(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:sql.sql_init.InitSize)
}
inline ::uint32_t sql_init::_internal_initsize() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.initsize_;
}
inline void sql_init::_internal_set_initsize(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.initsize_ = value;
}

// uint32 MaxSize = 7;
inline void sql_init::clear_maxsize() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.maxsize_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::uint32_t sql_init::maxsize() const {
  // @@protoc_insertion_point(field_get:sql.sql_init.MaxSize)
  return _internal_maxsize();
}
inline void sql_init::set_maxsize(::uint32_t value) {
  _internal_set_maxsize(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:sql.sql_init.MaxSize)
}
inline ::uint32_t sql_init::_internal_maxsize() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.maxsize_;
}
inline void sql_init::_internal_set_maxsize(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.maxsize_ = value;
}

// uint32 TimeMax = 8;
inline void sql_init::clear_timemax() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timemax_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline ::uint32_t sql_init::timemax() const {
  // @@protoc_insertion_point(field_get:sql.sql_init.TimeMax)
  return _internal_timemax();
}
inline void sql_init::set_timemax(::uint32_t value) {
  _internal_set_timemax(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:sql.sql_init.TimeMax)
}
inline ::uint32_t sql_init::_internal_timemax() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timemax_;
}
inline void sql_init::_internal_set_timemax(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timemax_ = value;
}

// uint32 TimeOut = 9;
inline void sql_init::clear_timeout() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timeout_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
inline ::uint32_t sql_init::timeout() const {
  // @@protoc_insertion_point(field_get:sql.sql_init.TimeOut)
  return _internal_timeout();
}
inline void sql_init::set_timeout(::uint32_t value) {
  _internal_set_timeout(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:sql.sql_init.TimeOut)
}
inline ::uint32_t sql_init::_internal_timeout() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timeout_;
}
inline void sql_init::_internal_set_timeout(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timeout_ = value;
}

// uint32 ThreadPoolSize = 10;
inline void sql_init::clear_threadpoolsize() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.threadpoolsize_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000200U);
}
inline ::uint32_t sql_init::threadpoolsize() const {
  // @@protoc_insertion_point(field_get:sql.sql_init.ThreadPoolSize)
  return _internal_threadpoolsize();
}
inline void sql_init::set_threadpoolsize(::uint32_t value) {
  _internal_set_threadpoolsize(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_set:sql.sql_init.ThreadPoolSize)
}
inline ::uint32_t sql_init::_internal_threadpoolsize() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.threadpoolsize_;
}
inline void sql_init::_internal_set_threadpoolsize(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.threadpoolsize_ = value;
}

// -------------------------------------------------------------------

// sql_insert

// .common.header head = 1;
inline bool sql_insert::has_head() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.head_ != nullptr);
  return value;
}
inline const ::common::header& sql_insert::_internal_head() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::common::header* p = _impl_.head_;
  return p != nullptr ? *p : reinterpret_cast<const ::common::header&>(::common::_header_default_instance_);
}
inline const ::common::header& sql_insert::head() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:sql.sql_insert.head)
  return _internal_head();
}
inline void sql_insert::unsafe_arena_set_allocated_head(
    ::common::header* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.head_);
  }
  _impl_.head_ = reinterpret_cast<::common::header*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sql.sql_insert.head)
}
inline ::common::header* PROTOBUF_NULLABLE sql_insert::release_head() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::common::header* released = _impl_.head_;
  _impl_.head_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::common::header* PROTOBUF_NULLABLE sql_insert::unsafe_arena_release_head() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:sql.sql_insert.head)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::common::header* temp = _impl_.head_;
  _impl_.head_ = nullptr;
  return temp;
}
inline ::common::header* PROTOBUF_NONNULL sql_insert::_internal_mutable_head() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.head_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::common::header>(GetArena());
    _impl_.head_ = reinterpret_cast<::common::header*>(p);
  }
  return _impl_.head_;
}
inline ::common::header* PROTOBUF_NONNULL sql_insert::mutable_head()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::common::header* _msg = _internal_mutable_head();
  // @@protoc_insertion_point(field_mutable:sql.sql_insert.head)
  return _msg;
}
inline void sql_insert::set_allocated_head(::common::header* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.head_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.head_ = reinterpret_cast<::common::header*>(value);
  // @@protoc_insertion_point(field_set_allocated:sql.sql_insert.head)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace sql


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // MySQL_2eproto_2epb_2eh
