// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MySQL.proto
// Protobuf C++ Version: 6.33.4

#include "MySQL.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace sql {

inline constexpr sql_init::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        ip_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        user_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        password_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        db_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        port_{0u},
        initsize_{0u},
        maxsize_{0u},
        timemax_{0u},
        timeout_{0u},
        threadpoolsize_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR sql_init::sql_init(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(sql_init_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct sql_initDefaultTypeInternal {
  PROTOBUF_CONSTEXPR sql_initDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~sql_initDefaultTypeInternal() {}
  union {
    sql_init _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 sql_initDefaultTypeInternal _sql_init_default_instance_;

inline constexpr sql_node::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        head_{nullptr},
        type_{0} {}

template <typename>
PROTOBUF_CONSTEXPR sql_node::sql_node(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(sql_node_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct sql_nodeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR sql_nodeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~sql_nodeDefaultTypeInternal() {}
  union {
    sql_node _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 sql_nodeDefaultTypeInternal _sql_node_default_instance_;

inline constexpr sql_insert::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        head_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR sql_insert::sql_insert(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(sql_insert_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct sql_insertDefaultTypeInternal {
  PROTOBUF_CONSTEXPR sql_insertDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~sql_insertDefaultTypeInternal() {}
  union {
    sql_insert _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 sql_insertDefaultTypeInternal _sql_insert_default_instance_;
}  // namespace sql
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_MySQL_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_MySQL_2eproto = nullptr;
const ::uint32_t
    TableStruct_MySQL_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::sql::sql_node, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::sql::sql_node, _impl_.head_),
        PROTOBUF_FIELD_OFFSET(::sql::sql_node, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::sql::sql_node, _impl_.msg_),
        1,
        2,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::sql::sql_init, _impl_._has_bits_),
        13, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::sql::sql_init, _impl_.ip_),
        PROTOBUF_FIELD_OFFSET(::sql::sql_init, _impl_.port_),
        PROTOBUF_FIELD_OFFSET(::sql::sql_init, _impl_.user_),
        PROTOBUF_FIELD_OFFSET(::sql::sql_init, _impl_.password_),
        PROTOBUF_FIELD_OFFSET(::sql::sql_init, _impl_.db_),
        PROTOBUF_FIELD_OFFSET(::sql::sql_init, _impl_.initsize_),
        PROTOBUF_FIELD_OFFSET(::sql::sql_init, _impl_.maxsize_),
        PROTOBUF_FIELD_OFFSET(::sql::sql_init, _impl_.timemax_),
        PROTOBUF_FIELD_OFFSET(::sql::sql_init, _impl_.timeout_),
        PROTOBUF_FIELD_OFFSET(::sql::sql_init, _impl_.threadpoolsize_),
        0,
        4,
        1,
        2,
        3,
        5,
        6,
        7,
        8,
        9,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::sql::sql_insert, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::sql::sql_insert, _impl_.head_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::sql::sql_node)},
        {9, sizeof(::sql::sql_init)},
        {32, sizeof(::sql::sql_insert)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::sql::_sql_node_default_instance_._instance,
    &::sql::_sql_init_default_instance_._instance,
    &::sql::_sql_insert_default_instance_._instance,
};
const char descriptor_table_protodef_MySQL_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013MySQL.proto\022\003sql\032\014Common.proto\"C\n\010sql_"
    "node\022\034\n\004head\030\001 \001(\0132\016.common.header\022\014\n\004ty"
    "pe\030\002 \001(\005\022\013\n\003msg\030\003 \001(\t\"\255\001\n\010sql_init\022\n\n\002ip"
    "\030\001 \001(\t\022\014\n\004port\030\002 \001(\r\022\014\n\004user\030\003 \001(\t\022\020\n\010pa"
    "ssword\030\004 \001(\t\022\n\n\002db\030\005 \001(\t\022\020\n\010InitSize\030\006 \001"
    "(\r\022\017\n\007MaxSize\030\007 \001(\r\022\017\n\007TimeMax\030\010 \001(\r\022\017\n\007"
    "TimeOut\030\t \001(\r\022\026\n\016ThreadPoolSize\030\n \001(\r\"*\n"
    "\nsql_insert\022\034\n\004head\030\001 \001(\0132\016.common.heade"
    "rb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_MySQL_2eproto_deps[1] = {
        &::descriptor_table_Common_2eproto,
};
static ::absl::once_flag descriptor_table_MySQL_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_MySQL_2eproto = {
    false,
    false,
    329,
    descriptor_table_protodef_MySQL_2eproto,
    "MySQL.proto",
    &descriptor_table_MySQL_2eproto_once,
    descriptor_table_MySQL_2eproto_deps,
    1,
    3,
    schemas,
    file_default_instances,
    TableStruct_MySQL_2eproto::offsets,
    file_level_enum_descriptors_MySQL_2eproto,
    file_level_service_descriptors_MySQL_2eproto,
};
namespace sql {
// ===================================================================

class sql_node::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<sql_node>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(sql_node, _impl_._has_bits_);
};

void sql_node::clear_head() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.head_ != nullptr) _impl_.head_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
sql_node::sql_node(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, sql_node_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sql.sql_node)
}
PROTOBUF_NDEBUG_INLINE sql_node::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::sql::sql_node& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        msg_(arena, from.msg_) {}

sql_node::sql_node(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const sql_node& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, sql_node_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  sql_node* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.head_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.head_)
                : nullptr;
  _impl_.type_ = from._impl_.type_;

  // @@protoc_insertion_point(copy_constructor:sql.sql_node)
}
PROTOBUF_NDEBUG_INLINE sql_node::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        msg_(arena) {}

inline void sql_node::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, head_),
           0,
           offsetof(Impl_, type_) -
               offsetof(Impl_, head_) +
               sizeof(Impl_::type_));
}
sql_node::~sql_node() {
  // @@protoc_insertion_point(destructor:sql.sql_node)
  SharedDtor(*this);
}
inline void sql_node::SharedDtor(MessageLite& self) {
  sql_node& this_ = static_cast<sql_node&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.msg_.Destroy();
  delete this_._impl_.head_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL sql_node::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) sql_node(arena);
}
constexpr auto sql_node::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(sql_node),
                                            alignof(sql_node));
}
constexpr auto sql_node::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_sql_node_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &sql_node::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<sql_node>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &sql_node::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<sql_node>(), &sql_node::ByteSizeLong,
              &sql_node::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(sql_node, _impl_._cached_size_),
          false,
      },
      &sql_node::kDescriptorMethods,
      &descriptor_table_MySQL_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull sql_node_class_data_ =
        sql_node::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
sql_node::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&sql_node_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(sql_node_class_data_.tc_table);
  return sql_node_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 24, 2>
sql_node::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(sql_node, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    sql_node_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::sql::sql_node>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .common.header head = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 1, 0,
      PROTOBUF_FIELD_OFFSET(sql_node, _impl_.head_)}},
    // int32 type = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(sql_node, _impl_.type_), 2>(),
     {16, 2, 0,
      PROTOBUF_FIELD_OFFSET(sql_node, _impl_.type_)}},
    // string msg = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 0, 0,
      PROTOBUF_FIELD_OFFSET(sql_node, _impl_.msg_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .common.header head = 1;
    {PROTOBUF_FIELD_OFFSET(sql_node, _impl_.head_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // int32 type = 2;
    {PROTOBUF_FIELD_OFFSET(sql_node, _impl_.type_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string msg = 3;
    {PROTOBUF_FIELD_OFFSET(sql_node, _impl_.msg_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::common::header>()},
  }},
  {{
    "\14\0\0\3\0\0\0\0"
    "sql.sql_node"
    "msg"
  }},
};
PROTOBUF_NOINLINE void sql_node::Clear() {
// @@protoc_insertion_point(message_clear_start:sql.sql_node)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.msg_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.head_ != nullptr);
      _impl_.head_->Clear();
    }
  }
  _impl_.type_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL sql_node::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const sql_node& this_ = static_cast<const sql_node&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL sql_node::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const sql_node& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:sql.sql_node)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .common.header head = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.head_, this_._impl_.head_->GetCachedSize(), target,
        stream);
  }

  // int32 type = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_type() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_type(), target);
    }
  }

  // string msg = 3;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_msg().empty()) {
      const ::std::string& _s = this_._internal_msg();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sql.sql_node.msg");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sql.sql_node)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t sql_node::ByteSizeLong(const MessageLite& base) {
  const sql_node& this_ = static_cast<const sql_node&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t sql_node::ByteSizeLong() const {
  const sql_node& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:sql.sql_node)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // string msg = 3;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_msg().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_msg());
      }
    }
    // .common.header head = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.head_);
    }
    // int32 type = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_type() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_type());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void sql_node::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<sql_node*>(&to_msg);
  auto& from = static_cast<const sql_node&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:sql.sql_node)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_msg().empty()) {
        _this->_internal_set_msg(from._internal_msg());
      } else {
        if (_this->_impl_.msg_.IsDefault()) {
          _this->_internal_set_msg("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.head_ != nullptr);
      if (_this->_impl_.head_ == nullptr) {
        _this->_impl_.head_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.head_);
      } else {
        _this->_impl_.head_->MergeFrom(*from._impl_.head_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_type() != 0) {
        _this->_impl_.type_ = from._impl_.type_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void sql_node::CopyFrom(const sql_node& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:sql.sql_node)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void sql_node::InternalSwap(sql_node* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.msg_, &other->_impl_.msg_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(sql_node, _impl_.type_)
      + sizeof(sql_node::_impl_.type_)
      - PROTOBUF_FIELD_OFFSET(sql_node, _impl_.head_)>(
          reinterpret_cast<char*>(&_impl_.head_),
          reinterpret_cast<char*>(&other->_impl_.head_));
}

::google::protobuf::Metadata sql_node::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class sql_init::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<sql_init>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(sql_init, _impl_._has_bits_);
};

sql_init::sql_init(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, sql_init_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sql.sql_init)
}
PROTOBUF_NDEBUG_INLINE sql_init::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::sql::sql_init& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        ip_(arena, from.ip_),
        user_(arena, from.user_),
        password_(arena, from.password_),
        db_(arena, from.db_) {}

sql_init::sql_init(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const sql_init& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, sql_init_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  sql_init* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, port_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, port_),
           offsetof(Impl_, threadpoolsize_) -
               offsetof(Impl_, port_) +
               sizeof(Impl_::threadpoolsize_));

  // @@protoc_insertion_point(copy_constructor:sql.sql_init)
}
PROTOBUF_NDEBUG_INLINE sql_init::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        ip_(arena),
        user_(arena),
        password_(arena),
        db_(arena) {}

inline void sql_init::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, port_),
           0,
           offsetof(Impl_, threadpoolsize_) -
               offsetof(Impl_, port_) +
               sizeof(Impl_::threadpoolsize_));
}
sql_init::~sql_init() {
  // @@protoc_insertion_point(destructor:sql.sql_init)
  SharedDtor(*this);
}
inline void sql_init::SharedDtor(MessageLite& self) {
  sql_init& this_ = static_cast<sql_init&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.ip_.Destroy();
  this_._impl_.user_.Destroy();
  this_._impl_.password_.Destroy();
  this_._impl_.db_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL sql_init::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) sql_init(arena);
}
constexpr auto sql_init::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(sql_init),
                                            alignof(sql_init));
}
constexpr auto sql_init::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_sql_init_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &sql_init::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<sql_init>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &sql_init::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<sql_init>(), &sql_init::ByteSizeLong,
              &sql_init::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(sql_init, _impl_._cached_size_),
          false,
      },
      &sql_init::kDescriptorMethods,
      &descriptor_table_MySQL_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull sql_init_class_data_ =
        sql_init::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
sql_init::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&sql_init_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(sql_init_class_data_.tc_table);
  return sql_init_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 10, 0, 45, 2>
sql_init::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(sql_init, _impl_._has_bits_),
    0, // no _extensions_
    10, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966272,  // skipmap
    offsetof(decltype(_table_), field_entries),
    10,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    sql_init_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::sql::sql_init>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string ip = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(sql_init, _impl_.ip_)}},
    // uint32 port = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(sql_init, _impl_.port_), 4>(),
     {16, 4, 0,
      PROTOBUF_FIELD_OFFSET(sql_init, _impl_.port_)}},
    // string user = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(sql_init, _impl_.user_)}},
    // string password = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 2, 0,
      PROTOBUF_FIELD_OFFSET(sql_init, _impl_.password_)}},
    // string db = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 3, 0,
      PROTOBUF_FIELD_OFFSET(sql_init, _impl_.db_)}},
    // uint32 InitSize = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(sql_init, _impl_.initsize_), 5>(),
     {48, 5, 0,
      PROTOBUF_FIELD_OFFSET(sql_init, _impl_.initsize_)}},
    // uint32 MaxSize = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(sql_init, _impl_.maxsize_), 6>(),
     {56, 6, 0,
      PROTOBUF_FIELD_OFFSET(sql_init, _impl_.maxsize_)}},
    // uint32 TimeMax = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(sql_init, _impl_.timemax_), 7>(),
     {64, 7, 0,
      PROTOBUF_FIELD_OFFSET(sql_init, _impl_.timemax_)}},
    // uint32 TimeOut = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(sql_init, _impl_.timeout_), 8>(),
     {72, 8, 0,
      PROTOBUF_FIELD_OFFSET(sql_init, _impl_.timeout_)}},
    // uint32 ThreadPoolSize = 10;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(sql_init, _impl_.threadpoolsize_), 9>(),
     {80, 9, 0,
      PROTOBUF_FIELD_OFFSET(sql_init, _impl_.threadpoolsize_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string ip = 1;
    {PROTOBUF_FIELD_OFFSET(sql_init, _impl_.ip_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 port = 2;
    {PROTOBUF_FIELD_OFFSET(sql_init, _impl_.port_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // string user = 3;
    {PROTOBUF_FIELD_OFFSET(sql_init, _impl_.user_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string password = 4;
    {PROTOBUF_FIELD_OFFSET(sql_init, _impl_.password_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string db = 5;
    {PROTOBUF_FIELD_OFFSET(sql_init, _impl_.db_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 InitSize = 6;
    {PROTOBUF_FIELD_OFFSET(sql_init, _impl_.initsize_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 MaxSize = 7;
    {PROTOBUF_FIELD_OFFSET(sql_init, _impl_.maxsize_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 TimeMax = 8;
    {PROTOBUF_FIELD_OFFSET(sql_init, _impl_.timemax_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 TimeOut = 9;
    {PROTOBUF_FIELD_OFFSET(sql_init, _impl_.timeout_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 ThreadPoolSize = 10;
    {PROTOBUF_FIELD_OFFSET(sql_init, _impl_.threadpoolsize_), _Internal::kHasBitsOffset + 9, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
    "\14\2\0\4\10\2\0\0\0\0\0\0\0\0\0\0"
    "sql.sql_init"
    "ip"
    "user"
    "password"
    "db"
  }},
};
PROTOBUF_NOINLINE void sql_init::Clear() {
// @@protoc_insertion_point(message_clear_start:sql.sql_init)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.ip_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.user_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.password_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.db_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000f0U)) {
    ::memset(&_impl_.port_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.timemax_) -
        reinterpret_cast<char*>(&_impl_.port_)) + sizeof(_impl_.timemax_));
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000300U)) {
    ::memset(&_impl_.timeout_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.threadpoolsize_) -
        reinterpret_cast<char*>(&_impl_.timeout_)) + sizeof(_impl_.threadpoolsize_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL sql_init::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const sql_init& this_ = static_cast<const sql_init&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL sql_init::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const sql_init& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:sql.sql_init)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string ip = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_ip().empty()) {
      const ::std::string& _s = this_._internal_ip();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sql.sql_init.ip");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // uint32 port = 2;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_port() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          2, this_._internal_port(), target);
    }
  }

  // string user = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_user().empty()) {
      const ::std::string& _s = this_._internal_user();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sql.sql_init.user");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // string password = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_password().empty()) {
      const ::std::string& _s = this_._internal_password();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sql.sql_init.password");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  // string db = 5;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_db().empty()) {
      const ::std::string& _s = this_._internal_db();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sql.sql_init.db");
      target = stream->WriteStringMaybeAliased(5, _s, target);
    }
  }

  // uint32 InitSize = 6;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_initsize() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          6, this_._internal_initsize(), target);
    }
  }

  // uint32 MaxSize = 7;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_maxsize() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          7, this_._internal_maxsize(), target);
    }
  }

  // uint32 TimeMax = 8;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (this_._internal_timemax() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          8, this_._internal_timemax(), target);
    }
  }

  // uint32 TimeOut = 9;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    if (this_._internal_timeout() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          9, this_._internal_timeout(), target);
    }
  }

  // uint32 ThreadPoolSize = 10;
  if (CheckHasBit(cached_has_bits, 0x00000200U)) {
    if (this_._internal_threadpoolsize() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          10, this_._internal_threadpoolsize(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sql.sql_init)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t sql_init::ByteSizeLong(const MessageLite& base) {
  const sql_init& this_ = static_cast<const sql_init&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t sql_init::ByteSizeLong() const {
  const sql_init& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:sql.sql_init)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // string ip = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_ip().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_ip());
      }
    }
    // string user = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_user().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_user());
      }
    }
    // string password = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_password().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_password());
      }
    }
    // string db = 5;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_db().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_db());
      }
    }
    // uint32 port = 2;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_port() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_port());
      }
    }
    // uint32 InitSize = 6;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_initsize() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_initsize());
      }
    }
    // uint32 MaxSize = 7;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_maxsize() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_maxsize());
      }
    }
    // uint32 TimeMax = 8;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (this_._internal_timemax() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_timemax());
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000300U)) {
    // uint32 TimeOut = 9;
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (this_._internal_timeout() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_timeout());
      }
    }
    // uint32 ThreadPoolSize = 10;
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (this_._internal_threadpoolsize() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_threadpoolsize());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void sql_init::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<sql_init*>(&to_msg);
  auto& from = static_cast<const sql_init&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:sql.sql_init)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_ip().empty()) {
        _this->_internal_set_ip(from._internal_ip());
      } else {
        if (_this->_impl_.ip_.IsDefault()) {
          _this->_internal_set_ip("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_user().empty()) {
        _this->_internal_set_user(from._internal_user());
      } else {
        if (_this->_impl_.user_.IsDefault()) {
          _this->_internal_set_user("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_password().empty()) {
        _this->_internal_set_password(from._internal_password());
      } else {
        if (_this->_impl_.password_.IsDefault()) {
          _this->_internal_set_password("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_db().empty()) {
        _this->_internal_set_db(from._internal_db());
      } else {
        if (_this->_impl_.db_.IsDefault()) {
          _this->_internal_set_db("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_port() != 0) {
        _this->_impl_.port_ = from._impl_.port_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_initsize() != 0) {
        _this->_impl_.initsize_ = from._impl_.initsize_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_maxsize() != 0) {
        _this->_impl_.maxsize_ = from._impl_.maxsize_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (from._internal_timemax() != 0) {
        _this->_impl_.timemax_ = from._impl_.timemax_;
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000300U)) {
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (from._internal_timeout() != 0) {
        _this->_impl_.timeout_ = from._impl_.timeout_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (from._internal_threadpoolsize() != 0) {
        _this->_impl_.threadpoolsize_ = from._impl_.threadpoolsize_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void sql_init::CopyFrom(const sql_init& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:sql.sql_init)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void sql_init::InternalSwap(sql_init* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ip_, &other->_impl_.ip_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.user_, &other->_impl_.user_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.password_, &other->_impl_.password_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.db_, &other->_impl_.db_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(sql_init, _impl_.threadpoolsize_)
      + sizeof(sql_init::_impl_.threadpoolsize_)
      - PROTOBUF_FIELD_OFFSET(sql_init, _impl_.port_)>(
          reinterpret_cast<char*>(&_impl_.port_),
          reinterpret_cast<char*>(&other->_impl_.port_));
}

::google::protobuf::Metadata sql_init::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class sql_insert::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<sql_insert>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(sql_insert, _impl_._has_bits_);
};

void sql_insert::clear_head() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.head_ != nullptr) _impl_.head_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
sql_insert::sql_insert(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, sql_insert_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sql.sql_insert)
}
PROTOBUF_NDEBUG_INLINE sql_insert::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::sql::sql_insert& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

sql_insert::sql_insert(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const sql_insert& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, sql_insert_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  sql_insert* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.head_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.head_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:sql.sql_insert)
}
PROTOBUF_NDEBUG_INLINE sql_insert::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void sql_insert::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.head_ = {};
}
sql_insert::~sql_insert() {
  // @@protoc_insertion_point(destructor:sql.sql_insert)
  SharedDtor(*this);
}
inline void sql_insert::SharedDtor(MessageLite& self) {
  sql_insert& this_ = static_cast<sql_insert&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.head_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL sql_insert::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) sql_insert(arena);
}
constexpr auto sql_insert::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(sql_insert),
                                            alignof(sql_insert));
}
constexpr auto sql_insert::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_sql_insert_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &sql_insert::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<sql_insert>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &sql_insert::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<sql_insert>(), &sql_insert::ByteSizeLong,
              &sql_insert::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(sql_insert, _impl_._cached_size_),
          false,
      },
      &sql_insert::kDescriptorMethods,
      &descriptor_table_MySQL_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull sql_insert_class_data_ =
        sql_insert::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
sql_insert::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&sql_insert_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(sql_insert_class_data_.tc_table);
  return sql_insert_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
sql_insert::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(sql_insert, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    sql_insert_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::sql::sql_insert>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .common.header head = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(sql_insert, _impl_.head_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .common.header head = 1;
    {PROTOBUF_FIELD_OFFSET(sql_insert, _impl_.head_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::common::header>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void sql_insert::Clear() {
// @@protoc_insertion_point(message_clear_start:sql.sql_insert)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    ABSL_DCHECK(_impl_.head_ != nullptr);
    _impl_.head_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL sql_insert::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const sql_insert& this_ = static_cast<const sql_insert&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL sql_insert::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const sql_insert& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:sql.sql_insert)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .common.header head = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.head_, this_._impl_.head_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sql.sql_insert)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t sql_insert::ByteSizeLong(const MessageLite& base) {
  const sql_insert& this_ = static_cast<const sql_insert&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t sql_insert::ByteSizeLong() const {
  const sql_insert& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:sql.sql_insert)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // .common.header head = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.head_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void sql_insert::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<sql_insert*>(&to_msg);
  auto& from = static_cast<const sql_insert&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:sql.sql_insert)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    ABSL_DCHECK(from._impl_.head_ != nullptr);
    if (_this->_impl_.head_ == nullptr) {
      _this->_impl_.head_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.head_);
    } else {
      _this->_impl_.head_->MergeFrom(*from._impl_.head_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void sql_insert::CopyFrom(const sql_insert& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:sql.sql_insert)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void sql_insert::InternalSwap(sql_insert* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.head_, other->_impl_.head_);
}

::google::protobuf::Metadata sql_insert::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace sql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_MySQL_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
