// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: User.proto
// Protobuf C++ Version: 6.33.4

#include "User.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace webuser {

inline constexpr WebUser::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        password_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        email_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        head_{nullptr},
        uid_{0u},
        permissions_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR WebUser::WebUser(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(WebUser_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct WebUserDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WebUserDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WebUserDefaultTypeInternal() {}
  union {
    WebUser _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WebUserDefaultTypeInternal _WebUser_default_instance_;
}  // namespace webuser
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_User_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_User_2eproto = nullptr;
const ::uint32_t
    TableStruct_User_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::webuser::WebUser, _impl_._has_bits_),
        9, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::webuser::WebUser, _impl_.head_),
        PROTOBUF_FIELD_OFFSET(::webuser::WebUser, _impl_.uid_),
        PROTOBUF_FIELD_OFFSET(::webuser::WebUser, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::webuser::WebUser, _impl_.password_),
        PROTOBUF_FIELD_OFFSET(::webuser::WebUser, _impl_.email_),
        PROTOBUF_FIELD_OFFSET(::webuser::WebUser, _impl_.permissions_),
        3,
        4,
        0,
        1,
        2,
        5,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::webuser::WebUser)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::webuser::_WebUser_default_instance_._instance,
};
const char descriptor_table_protodef_User_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\nUser.proto\022\007webuser\032\014Common.proto\"x\n\007W"
    "ebUser\022\034\n\004head\030\001 \001(\0132\016.common.header\022\013\n\003"
    "UID\030\002 \001(\r\022\014\n\004name\030\003 \001(\t\022\020\n\010password\030\004 \001("
    "\t\022\r\n\005email\030\005 \001(\t\022\023\n\013permissions\030\006 \001(\rb\006p"
    "roto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_User_2eproto_deps[1] = {
        &::descriptor_table_Common_2eproto,
};
static ::absl::once_flag descriptor_table_User_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_User_2eproto = {
    false,
    false,
    165,
    descriptor_table_protodef_User_2eproto,
    "User.proto",
    &descriptor_table_User_2eproto_once,
    descriptor_table_User_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_User_2eproto::offsets,
    file_level_enum_descriptors_User_2eproto,
    file_level_service_descriptors_User_2eproto,
};
namespace webuser {
// ===================================================================

class WebUser::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<WebUser>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(WebUser, _impl_._has_bits_);
};

void WebUser::clear_head() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.head_ != nullptr) _impl_.head_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
WebUser::WebUser(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WebUser_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:webuser.WebUser)
}
PROTOBUF_NDEBUG_INLINE WebUser::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::webuser::WebUser& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_),
        password_(arena, from.password_),
        email_(arena, from.email_) {}

WebUser::WebUser(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const WebUser& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WebUser_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  WebUser* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.head_ = (CheckHasBit(cached_has_bits, 0x00000008U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.head_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, uid_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, uid_),
           offsetof(Impl_, permissions_) -
               offsetof(Impl_, uid_) +
               sizeof(Impl_::permissions_));

  // @@protoc_insertion_point(copy_constructor:webuser.WebUser)
}
PROTOBUF_NDEBUG_INLINE WebUser::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena),
        password_(arena),
        email_(arena) {}

inline void WebUser::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, head_),
           0,
           offsetof(Impl_, permissions_) -
               offsetof(Impl_, head_) +
               sizeof(Impl_::permissions_));
}
WebUser::~WebUser() {
  // @@protoc_insertion_point(destructor:webuser.WebUser)
  SharedDtor(*this);
}
inline void WebUser::SharedDtor(MessageLite& self) {
  WebUser& this_ = static_cast<WebUser&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.password_.Destroy();
  this_._impl_.email_.Destroy();
  delete this_._impl_.head_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL WebUser::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) WebUser(arena);
}
constexpr auto WebUser::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(WebUser),
                                            alignof(WebUser));
}
constexpr auto WebUser::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_WebUser_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &WebUser::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<WebUser>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &WebUser::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<WebUser>(), &WebUser::ByteSizeLong,
              &WebUser::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(WebUser, _impl_._cached_size_),
          false,
      },
      &WebUser::kDescriptorMethods,
      &descriptor_table_User_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull WebUser_class_data_ =
        WebUser::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
WebUser::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&WebUser_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(WebUser_class_data_.tc_table);
  return WebUser_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 1, 41, 2>
WebUser::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(WebUser, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    WebUser_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::webuser::WebUser>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .common.header head = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 3, 0,
      PROTOBUF_FIELD_OFFSET(WebUser, _impl_.head_)}},
    // uint32 UID = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(WebUser, _impl_.uid_), 4>(),
     {16, 4, 0,
      PROTOBUF_FIELD_OFFSET(WebUser, _impl_.uid_)}},
    // string name = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 0, 0,
      PROTOBUF_FIELD_OFFSET(WebUser, _impl_.name_)}},
    // string password = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 1, 0,
      PROTOBUF_FIELD_OFFSET(WebUser, _impl_.password_)}},
    // string email = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 2, 0,
      PROTOBUF_FIELD_OFFSET(WebUser, _impl_.email_)}},
    // uint32 permissions = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(WebUser, _impl_.permissions_), 5>(),
     {48, 5, 0,
      PROTOBUF_FIELD_OFFSET(WebUser, _impl_.permissions_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .common.header head = 1;
    {PROTOBUF_FIELD_OFFSET(WebUser, _impl_.head_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // uint32 UID = 2;
    {PROTOBUF_FIELD_OFFSET(WebUser, _impl_.uid_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // string name = 3;
    {PROTOBUF_FIELD_OFFSET(WebUser, _impl_.name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string password = 4;
    {PROTOBUF_FIELD_OFFSET(WebUser, _impl_.password_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string email = 5;
    {PROTOBUF_FIELD_OFFSET(WebUser, _impl_.email_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 permissions = 6;
    {PROTOBUF_FIELD_OFFSET(WebUser, _impl_.permissions_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::common::header>()},
  }},
  {{
    "\17\0\0\4\10\5\0\0"
    "webuser.WebUser"
    "name"
    "password"
    "email"
  }},
};
PROTOBUF_NOINLINE void WebUser::Clear() {
// @@protoc_insertion_point(message_clear_start:webuser.WebUser)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.password_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.email_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(_impl_.head_ != nullptr);
      _impl_.head_->Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000030U)) {
    ::memset(&_impl_.uid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.permissions_) -
        reinterpret_cast<char*>(&_impl_.uid_)) + sizeof(_impl_.permissions_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL WebUser::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const WebUser& this_ = static_cast<const WebUser&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL WebUser::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const WebUser& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:webuser.WebUser)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .common.header head = 1;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.head_, this_._impl_.head_->GetCachedSize(), target,
        stream);
  }

  // uint32 UID = 2;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_uid() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          2, this_._internal_uid(), target);
    }
  }

  // string name = 3;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_name().empty()) {
      const ::std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "webuser.WebUser.name");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // string password = 4;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_password().empty()) {
      const ::std::string& _s = this_._internal_password();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "webuser.WebUser.password");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  // string email = 5;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_email().empty()) {
      const ::std::string& _s = this_._internal_email();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "webuser.WebUser.email");
      target = stream->WriteStringMaybeAliased(5, _s, target);
    }
  }

  // uint32 permissions = 6;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_permissions() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          6, this_._internal_permissions(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:webuser.WebUser)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t WebUser::ByteSizeLong(const MessageLite& base) {
  const WebUser& this_ = static_cast<const WebUser&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t WebUser::ByteSizeLong() const {
  const WebUser& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:webuser.WebUser)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    // string name = 3;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_name());
      }
    }
    // string password = 4;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_password().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_password());
      }
    }
    // string email = 5;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_email().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_email());
      }
    }
    // .common.header head = 1;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.head_);
    }
    // uint32 UID = 2;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_uid() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_uid());
      }
    }
    // uint32 permissions = 6;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_permissions() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_permissions());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void WebUser::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<WebUser*>(&to_msg);
  auto& from = static_cast<const WebUser&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:webuser.WebUser)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_name().empty()) {
        _this->_internal_set_name(from._internal_name());
      } else {
        if (_this->_impl_.name_.IsDefault()) {
          _this->_internal_set_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_password().empty()) {
        _this->_internal_set_password(from._internal_password());
      } else {
        if (_this->_impl_.password_.IsDefault()) {
          _this->_internal_set_password("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_email().empty()) {
        _this->_internal_set_email(from._internal_email());
      } else {
        if (_this->_impl_.email_.IsDefault()) {
          _this->_internal_set_email("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(from._impl_.head_ != nullptr);
      if (_this->_impl_.head_ == nullptr) {
        _this->_impl_.head_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.head_);
      } else {
        _this->_impl_.head_->MergeFrom(*from._impl_.head_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_uid() != 0) {
        _this->_impl_.uid_ = from._impl_.uid_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_permissions() != 0) {
        _this->_impl_.permissions_ = from._impl_.permissions_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void WebUser::CopyFrom(const WebUser& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:webuser.WebUser)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WebUser::InternalSwap(WebUser* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.password_, &other->_impl_.password_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.email_, &other->_impl_.email_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(WebUser, _impl_.permissions_)
      + sizeof(WebUser::_impl_.permissions_)
      - PROTOBUF_FIELD_OFFSET(WebUser, _impl_.head_)>(
          reinterpret_cast<char*>(&_impl_.head_),
          reinterpret_cast<char*>(&other->_impl_.head_));
}

::google::protobuf::Metadata WebUser::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace webuser
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_User_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
